### ISSUE TITLE
Port from Kraken to Helix

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#13]
When Kraken gets phased out, and assuming that Helix adopts all the endpoints that Kraken has by the end of this year, then will this package seamlessly migrate from Kraken to Helix in the backend? 

Meaning, if I make a call to `streams.getAllLiveStreams`, which I assume uses Kraken for now, then will it eventually use Helix when that's available, and all I have to do on my end is update my version of this package? Assuming they have the same response of course; otherwise, I guess this package could just map the new keys to the old ones.

And is there a way to manually switch between the two APIs?

**Comment by d-fischer** [comment]
Currently all Helix methods live under `client.helix`.
I think it's not a good thing if I just keep the names as they are now when I port over to Helix. The data structures are too different and things _will_ break - just not as obviously as a "method not found" error. I'd rather break obviously rather than hidden.
