### ISSUE TITLE
PubSub client subscribing on auth provided channel instead of passed

### ISSUE THREAD

**Issue by Satont** [d-fischer/twitch#173]
### Code

```ts
this.client = new PubSubClient()
await this.client.registerUserListener(tmi.clients.bot, 128644134)
const r = await this.client.onRedemption(128644134, () => {})
console.log(r, r.userId)
```
Where `tmi.clients.bot` is `ApiClient` instance.
Result of console.log:
```
PubSubListener {
  _type: 'channel-points-channel-v1',
  _userId: '549892689',
  _callback: [Function (anonymous)],
  _client: SingleUserPubSubClient {
    _listeners: Map(1) { 'channel-points-channel-v1' => [Array] },
    _userId: '549892689'
  }
} 549892689
```

or for bigger pieces of code, create a new GitHub repository we can clone to reproduce the problem.
-->

### Expected behavior

I'm except listen PubSub events from passed channel.

### Actual Behavior

As you can see, userId is `549892689`, what is id of my bot, instead of `128644134`

So, PubSub listening events on bot channel, instead of channel i passed as argument

### Environment

- Version: pubsub 4.2.2, twitch-api 4.2.2, twitch-chat 4.2.2
- Node version: 14.9.0
- Browser version: 
- Operating system: WSL v1

**Comment by d-fischer** [comment]
This is working as expected.

The ID you pass (by the way, it should be a string, not a number) is just an internal identifier for the client. You're not supposed to pass it at all unless it's 100% clear that it **matches the authenticated user** (i.e. you just did a validate call), in which case you can pass it to save the internal call to the same resource.
This is stated [in the docs](https://d-fischer.github.io/twitch-pubsub-client/reference/classes/PubSubClient.html#registerUserListener).

Enabling you to pass a different user ID all the way through to the topic name would serve no purpose, since you can't listen to topics of other users. To listen to a channel's redemptions (or any other topics, for that matter), you must be authenticated as that channel.
