### ISSUE TITLE
Provide prebuild/package as es6 module

### ISSUE THREAD

**Issue by mix3d** [d-fischer/twitch#187]
## Feature Request
Being able to import the project as a single package directly into an html page, without having to use a bundler, etc, would be really nice.

**Comment by freaktechnik** [comment]
That's already available in the es folder with the node `.mjs` file extension: https://unpkg.com/browse/twitch@4.3.2/es/

**Comment by d-fischer** [comment]
Your request is conflicting itself. ES6 modules don't usually come bundled as single files.
Since you're stating "without using a bundler", I assume you actually want UMD builds.

If you actually meant ES modules, they already exist, like @freaktechnik mentioned, but as I said, they're not single files.
Consider checking out [snowpack](https://www.snowpack.dev/) for working with these.

Please clarify what you mean.

**Comment by d-fischer** [comment]
Closing this because no clarification was provided. If you want this reopened, please respond.
