### ISSUE TITLE
Compatibility with deno.land

### ISSUE THREAD

**Issue by evandikt** [d-fischer/twitch#208]
It is possible to add the possibility to use this package with deno.land?

https://deno.land/

**Comment by d-fischer** [comment]
Please refer to this article: https://medium.com/samsung-internet-dev/using-node-modules-in-deno-2885600ed7a9

Main points:
- using Node modules with Deno is a bad practice
- You *might* be able to make it work using JSPM, but this package uses some Node-native packages, so it probably fails

Due to Node-native packages being used, this probably can never work with Deno out of the box.

Generally, I have never felt good about Deno explicitly and willingly not supporting the Node ecosystem and leaving people to resort to half-baked workarounds like this.

I'll leave this open at your discretion, in case you have a good way of implementing Deno compatibility without breaking any Node usage (and are ready to contribute - I don't have the time to invest into this). If this stays open for more than a week or so without a response to it, I'm going to close it.

**Comment by evandikt** [comment]
@d-fischer I don't think I'll contributing at the moment, I'm still learning about the ecosystem and how deno works ...
