### ISSUE TITLE
Helix GetFollows does not store the total results returned from the Twitch API

### ISSUE THREAD

**Issue by Spidy88** [d-fischer/twitch#22]
## Feature Request

The Twitch API includes a total results property to give developers an idea of how many pages there are in total. Unfortunately this value is not stored or made accessible in the current library. I find myself in a similar situation now where I want to query for followers but only care about the total number of followers (not the individual follower's information). In this case, I'd like to be able to set the results limit to 1, and grab the total value from the first query (essentially not using the pagination at all).

Here's an example of the response from Twitch:
```
{
   "total": 12345,
   "data":
   [
      {
         "from_id": "171003792",
         "from_name": "IIIsutha067III",
         "to_id": "23161357",
         "to_name": "LIRIK",
         "followed_at": "2017-08-22T22:55:24Z"
      },
      {
         "from_id": "113627897",
         "from_name": "Birdman616",
         "to_id": "23161357",
         "to_name": "LIRIK",
         "followed_at": "2017-08-22T22:55:04Z"
      },
      ...
   ],
   "pagination":{
     "cursor": "eyJiIjpudWxsLCJhIjoiMTUwMzQ0MTc3NjQyNDQyMjAwMCJ9"
   }
}```

**Comment by d-fischer** [comment]
Thanks for reporting! I will look into it tomorrow as it sounds like a fairly common use case :smiley:

**Comment by Spidy88** [comment]
Did a little more digging on the specifics. Looks like there are only 3 API endpoints that provide a `total` for the paginated data.

- https://dev.twitch.tv/docs/api/reference/#get-bits-leaderboard
- https://dev.twitch.tv/docs/api/reference/#get-users-follows
- https://dev.twitch.tv/docs/api/reference/#get-webhook-subscriptions

**Comment by d-fischer** [comment]
Thanks for the help!

- `HelixBitsAPI#getLeaderboard` already had support for the total count as it does not have cursor pagination.
- `HelixUserAPI#getFollows` now returns (instead of a `HelixPaginatedRequest`) an instance of the new subclass `HelixPaginatedRequestWithTotal` which supports the method `getTotalCount` to retrieve the total number of results.
- There's no WebHook support currently (although that's subject to change, and the corresponding method will definitely also return an instance of the new class) :smiley: 

A new version will be released on npm in a bit.
