### ISSUE TITLE
onRefresh function not calling and refresh_token is empty in getAccessToken()

### ISSUE THREAD

**Issue by T1MOXA** [d-fischer/twitch#75]
### Code

```js
const TwitchClient = require('twitch').default;

const TEST_CASE = 1;

const clientId = 'uo6dggojyb8d6soh92zknwmi5ej1q2';
const authToken = 'qwertyuiopasdf1234567890';
const clientSecret = 'nyo51xcdrerl8z9m56w9w6wg';
const refreshToken = 'uo6dggojyb8d6soh92zknwmi5ej1q2uo6dggojyb8d6soh92zknwmi5ej1q2';

TwitchClient.withCredentials(clientId, authToken, undefined, {
	clientSecret,
	refreshToken,
	onRefresh: (token) => {
		console.log('onRefresh', token);
	}
}).then(twitchClient => {
	if (TEST_CASE === 1) {
		twitchClient.getAccessToken().then(token => {
			console.log('getAccessToken', token);
		});
	} else if (TEST_CASE === 2) {
		twitchClient.refreshAccessToken().then(token => {
			console.log('refreshAccessToken', token);
		});
	}
});
```
With `TEST_CASE  = 1` and `onRefresh` function simply not calling, and `getAccessToken()` gives new token, but `refresh_token` key is empty.
But with `TEST_CASE  = 2`, callback works as it should and refresh_token present in response.

And yes, acess_token that I pass to `withCredentials` not working.

### Environment

- Version: 3.5.6, 3.7.0
- Node version: v12.9.1, v12.14.1, v13.7.0
- Operating system: Windows 10, Ubuntu 18.04

**Comment by d-fischer** [comment]
Fixed in 3.7.1.
This is not a problem in 4.x as the initialization process does not include a token check via the Twitch API anymore.

You actually had a bug in your code because if you passed an invalid (in the real world, expired?) token but no value for `expiry`, `getAccessToken()` will not refresh the token on its own, since it assumes that the token is valid indefinitely (which is actually the case with older apps).
But the token was still refreshed because of said token check, which will not exist anymore.

You have three options:
- Pass a value for `expiry`
- Don't pass any access token, only a refresh token
- Don't call `getAccessToken()` directly - out of curiosity, what is your use case for calling it directly? All API, chat, PubSub and WebHook methods manage their token handling internally.
